# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_text', models.TextField()),
                ('local_url', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField()),
            ],
        ),
    ]
